apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prakash-billing-dashboard.fullname" . }}-pvc
  labels:
    {{- include "prakash-billing-dashboard.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
